apiVersion: v2
name: external-ddns
description: Observes and corroborates a site's public address and publishes it through external-dns.
type: application
version: 0.1.1
appVersion: "0.1.1"
kubeVersion: ">=1.28.0-0"
home: https://github.com/reidops/external-ddns
sources:
  - https://github.com/reidops/external-ddns
keywords:
  - ddns
  - external-dns
  - kubernetes-operator
